// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/xtensor.h"
#include <Rcpp.h>

using namespace Rcpp;

// xtensor_r_example
xt::rtensor<double, 2> xtensor_r_example(xt::rtensor<int, 1> tens);
RcppExport SEXP _xtensor_xtensor_r_example(SEXP tensSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< xt::rtensor<int, 1> >::type tens(tensSEXP);
    rcpp_result_gen = Rcpp::wrap(xtensor_r_example(tens));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_xtensor_xtensor_r_example", (DL_FUNC) &_xtensor_xtensor_r_example, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_xtensor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
