# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

xtensor_r_example <- function(tens) {
    .Call('_xtensor_xtensor_r_example', PACKAGE = 'xtensor', tens)
}

